"""added uniqueConstraint for Store.title

Revision ID: 026592815b8e
Revises: 03e349ceca38
Create Date: 2022-01-26 00:30:20.659147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026592815b8e'
down_revision = '03e349ceca38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stores', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='unique')
    # ### end Alembic commands ###
